state_to_abbrev = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "District of Columbia": "DC",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
}

dem_win_by_state = [
    ("AK", 0),
    ("AL", 0),
    ("AR", 0),
    ("AZ", 1),
    ("CA", 1),
    ("CO", 1),
    ("CT", 1),
    ("DC", 1),
    ("DE", 1),
    ("FL", 0),
    ("GA", 0),
    ("HI", 1),
    ("IA", 0),
    ("ID", 0),
    ("IL", 1),
    ("IN", 0),
    ("KS", 0),
    ("KY", 0),
    ("LA", 0),
    ("MA", 1),
    ("MD", 1),
    ("ME", 1),
    ("MI", 1),
    ("MN", 1),
    ("MO", 0),
    ("MS", 0),
    ("MT", 0),
    ("NC", 0),
    ("ND", 0),
    ("NE", 0),
    ("NH", 1),
    ("NJ", 1),
    ("NM", 1),
    ("NV", 1),
    ("NY", 1),
    ("OH", 0),
    ("OK", 0),
    ("OR", 1),
    ("PA", 0),
    ("RI", 1),
    ("SC", 0),
    ("SD", 0),
    ("TN", 0),
    ("TX", 0),
    ("UT", 0),
    ("VA", 1),
    ("VT", 1),
    ("WA", 1),
    ("WI", 1),
    ("WV", 0),
    ("WY", 0),
]
